name: Build Chrome Extension

# Trigger workflow on push to main or pull request
on:
  push:
    branches: [  '**' ]
  pull_request:
    branches: [  '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # 3. Install npm dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run Webpack production build
      - name: Run production build
        run: npm run build

      # 5. Upload build artifacts
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chrome-extension-build
          path: dist/
